name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          - {os: macos-latest,    r: 'release'}
          - {os: windows-latest,  r: 'release'}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
      - name: Check
        run: R CMD check --as-cran .
